server:
  port: 8080

auth:
  url: http://localhost:8083
---

spring:
  cloud:
    gateway:
      routes:
        # Harmony
        - id: harmonic-fields-by-tone
          uri: http://192.168.0.109:8081
          predicates:
            - Path=/tones/{tone}/harmonic-fields/{type}
            - Method=GET
        # User Registration
        - id: create-user
          uri: http://192.168.0.109:8082
          predicates:
            - Path=/users
            - Method=POST

        - id: update-user
          uri: http://192.168.0.109:8082
          predicates:
            - Path=/users/{id}
            - Method=PATCH
          filters:
            - name: AuthorizationFilter
              args:
                role: USER

        - id: find-user-by-id
          uri: http://192.168.0.109:8082
          predicates:
            - Path=/users/{credentialId}
            - Method=GET
          filters:
            - name: AuthorizationFilter
              args:
                role: USER

        - id: delete-user-by-id
          uri: http://192.168.0.109:8082
          predicates:
            - Path=/users/{id}
            - Method=DELETE
          filters:
            - name: AuthorizationFilter
              args:
                role: USER

        #Auth-Service
        - id: authenticate
          uri: http://192.168.0.109:8083
          predicates:
            - Path=/authentications
            - Method=POST
        - id: get-credential-by-id
          uri: http://192.168.0.109:8083
          predicates:
            - Path=/credentials/{id}
            - Method=GET
          filters:
            - name: AuthorizationFilter
              args:
                role: USER
        - id: update-credential
          uri: http://192.168.0.109:8083
          predicates:
            - Path=/credentials/{id}
            - Method=PATCH
          filters:
            - name: AuthorizationFilter
              args:
                role: USER
        - id: request-password-recovery
          uri: http://192.168.0.109:8083
          predicates:
            - Path=/passwords/recoveries
            - Method=POST
        - id: create-password
          uri: http://192.168.0.109:8083
          predicates:
            - Path=/passwords
            - Method=POST